version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TEST: 'TEST'
    image: mwb-api
    networks:
    - mwb-workspace
    ports:
    - '4040:4040'
    volumes:
    - $PWD/index.js:/app/index.js
    - $PWD/utils.js:/app/utils.js
    - $PWD/models:/app/models
    - $PWD/controllers:/app/controllers
    - $PWD/middleware:/app/middleware
    - $PWD/configs:/app/configs
networks:
  mwb-workspace:
    name: mwb-workspace
