apiVersion: v1
kind: Service
metadata:
  labels:
    app: mwbank
  name: mwbank
spec:
  selector:
    app: mwbank
  ports:
  - port: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: mwbank
spec:
  host: api.nub.international
  service: mwbank:8080
  prefix: /
