apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: mwbank
  name: update-cron
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: gcr.io/main-219410/mw-bank-api:latest
            command: ['node']
            args: ['/app/update-cron.js']
            imagePullPolicy: Always
            name: update-cron
            env:
            - name: MWB_MONGO
              value: "mongodb://mongo-0.mongo.default.svc.cluster.local/mWorldProd"
            resources:
              requests:
                cpu: 10m
          restartPolicy: OnFailure
